server:
  port: 9004

spring:
  application:
    name: "service-booking"
  boot:
    admin:
      client:
        url: http://localhost:7021

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
