server:
  port: 9002

spring:
  application:
    name: "service-movie"
  boot:
    admin:
      client:
        url: http://localhost:7021

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
